# This file is part of the Admin Bundle.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

services:
    lin3s_admin.list_filter_type.text:
        class: LIN3S\AdminBundle\Extension\ListFilter\TextListFilterType
        tags:
            - {name: lin3s_admin.list_filter_type, alias: text}

    lin3s_admin.list_field_type.date:
        class: LIN3S\AdminBundle\Extension\ListField\DateListFieldType
        arguments:
            - "@translator"
        tags:
            - {name: lin3s_admin.list_filter_date, alias: date}
