# This file is part of the Shared Kernel library.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    lin3s_admin.pdo.connection_factory:
        class: LIN3S\AdminBundle\Repository\ConnectionFactory
        public: false
        arguments:
            - "%database_driver%"
            - "%database_name%"
            - "%database_host%"
            - "%database_port%"
            - "%database_user%"
            - "%database_password%"

    lin3s_admin.pdo:
        class: \PDO
        factory:
            - "@lin3s_admin.pdo.connection_factory"
            - "createConnection"
