# This file is part of the Admin Bundle.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

imports:
    - { resource: pdo.yml }

services:
    lin3s_admin.doctrine_repository:
        class: LIN3S\AdminBundle\Repository\DoctrineAdminRepository
        arguments:
            - '@doctrine.orm.entity_manager'
