# This file is part of the Admin Bundle.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

imports:
    - { resource: services/list_fields.yml }
    - { resource: services/list_filters.yml }
    - { resource: services/registry.yml }
    - { resource: services/repository.yml }
    - { resource: services/twig.yml }

services:
    lin3s_admin.configuration.factory.entity:
        class: LIN3S\AdminBundle\Configuration\Factory\EntityConfigurationFactory
        arguments:
            - '%lin3s_admin.config%'
            - '@lin3s_admin.action.registry'
            - '@lin3s_admin.list_field_type.registry'
            - '@lin3s_admin.list_filter_type.registry'

    lin3s_admin.form.handler:
        class: LIN3S\AdminBundle\Form\FormHandler
        arguments:
            - '@form.factory'
            - '@doctrine.orm.default_entity_manager'
